"""add_interval_to_alerts

Revision ID: 374956f06596
Revises: 20251230_002
Create Date: 2025-12-30 22:07:58.935952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '374956f06596'
down_revision: Union[str, Sequence[str], None] = '20251230_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_alerttrigger_alert_id', table_name='alerttrigger')
    op.drop_index('ix_alerttrigger_id', table_name='alerttrigger')
    op.drop_index('ix_alerttrigger_triggered_at', table_name='alerttrigger')
    op.drop_table('alerttrigger')
    # Add interval column nullable first, then update existing rows, then set NOT NULL
    op.add_column('alert', sa.Column('interval', sa.String(length=10), nullable=True))
    # Update existing rows to have a default interval
    op.execute("UPDATE alert SET interval = '1d' WHERE interval IS NULL")
    # Now set NOT NULL
    op.alter_column('alert', 'interval', nullable=False)
    op.alter_column('alert', 'uuid',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alert', 'cooldown',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Cooldown period in minutes (default: 1)',
               existing_nullable=True)
    op.drop_index('idx_alert_updated_at', table_name='alert')
    op.drop_index('idx_alert_user_id', table_name='alert')
    op.drop_index('idx_alert_user_uuid', table_name='alert')
    op.drop_index('ix_alerts_enabled_conditions', table_name='alert', postgresql_using='gin')
    op.drop_index('ix_alerts_indicator_name', table_name='alert', postgresql_where='(indicator_name IS NOT NULL)')
    op.create_index(op.f('ix_alert_user_id'), 'alert', ['user_id'], unique=False)
    op.alter_column('alert_trigger', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alert_trigger', 'observed_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index('ix_alert_triggers_delivery_status', table_name='alert_trigger', postgresql_where="((delivery_status)::text = ANY ((ARRAY['pending'::character varying, 'retrying'::character varying])::text[]))")
    op.alter_column('candle', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_candle_id', table_name='candle')
    op.drop_constraint('uq_candle_symbol_interval_timestamp', 'candle', type_='unique')
    op.create_unique_constraint('uix_candle_symbol_timestamp_interval', 'candle', ['symbol_id', 'timestamp', 'interval'])
    op.drop_column('candle', 'id')
    op.create_index(op.f('ix_ticker_universe_id'), 'ticker_universe', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_index(op.f('ix_ticker_universe_id'), table_name='ticker_universe')
    op.add_column('candle', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('uix_candle_symbol_timestamp_interval', 'candle', type_='unique')
    op.create_unique_constraint('uq_candle_symbol_interval_timestamp', 'candle', ['symbol_id', 'interval', 'timestamp'])
    op.create_index('ix_candle_id', 'candle', ['id'], unique=False)
    op.alter_column('candle', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_alert_triggers_delivery_status', 'alert_trigger', ['delivery_status', 'retry_count'], unique=False, postgresql_where="((delivery_status)::text = ANY ((ARRAY['pending'::character varying, 'retrying'::character varying])::text[]))")
    op.alter_column('alert_trigger', 'observed_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('alert_trigger', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_alert_user_id'), table_name='alert')
    op.create_index('ix_alerts_indicator_name', 'alert', ['indicator_name'], unique=False, postgresql_where='(indicator_name IS NOT NULL)')
    op.create_index('ix_alerts_enabled_conditions', 'alert', ['enabled_conditions'], unique=False, postgresql_using='gin')
    op.create_index('idx_alert_user_uuid', 'alert', ['user_id', 'uuid'], unique=False)
    op.create_index('idx_alert_user_id', 'alert', ['user_id'], unique=False)
    op.create_index('idx_alert_updated_at', 'alert', ['updated_at'], unique=False)
    op.alter_column('alert', 'cooldown',
               existing_type=sa.INTEGER(),
               comment='Cooldown period in minutes (default: 1)',
               existing_nullable=True)
    op.alter_column('alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alert', 'uuid',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('alert', 'interval')
    op.create_table('alerttrigger',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('observed_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name='alerttrigger_alert_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alerttrigger_pkey')
    )
    op.create_index('ix_alerttrigger_triggered_at', 'alerttrigger', ['triggered_at'], unique=False)
    op.create_index('ix_alerttrigger_id', 'alerttrigger', ['id'], unique=False)
    op.create_index('ix_alerttrigger_alert_id', 'alerttrigger', ['alert_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
