"""Add indicator_configs table

Revision ID: 4f93daae7d5c
Revises: a469670bd6a4
Create Date: 2026-01-04 09:42:03.726343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f93daae7d5c'
down_revision: Union[str, Sequence[str], None] = 'a469670bd6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('indicator_category', sa.String(length=20), nullable=False),
    sa.Column('indicator_params', sa.JSON(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'uuid', name='uq_indicator_config_user_uuid')
    )
    op.create_index(op.f('ix_indicator_configs_id'), 'indicator_configs', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_configs_indicator_name'), 'indicator_configs', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_indicator_configs_user_id'), 'indicator_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_alert_notification_settings_alert_id'), 'alert_notification_settings', ['alert_id'], unique=True)
    op.drop_constraint('alert_notification_settings_alert_id_fkey', 'alert_notification_settings', type_='foreignkey')
    op.create_foreign_key(None, 'alert_notification_settings', 'alert', ['alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alert_notification_settings', type_='foreignkey')
    op.create_foreign_key('alert_notification_settings_alert_id_fkey', 'alert_notification_settings', 'alert', ['alert_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alert_notification_settings_alert_id'), table_name='alert_notification_settings')
    op.drop_index(op.f('ix_indicator_configs_user_id'), table_name='indicator_configs')
    op.drop_index(op.f('ix_indicator_configs_indicator_name'), table_name='indicator_configs')
    op.drop_index(op.f('ix_indicator_configs_id'), table_name='indicator_configs')
    op.drop_table('indicator_configs')
    # ### end Alembic commands ###
