"""expand_candles_table

Revision ID: 60c50f0d4693
Revises: 5f5e25387acc
Create Date: 2025-12-22 10:29:19.372628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c50f0d4693'
down_revision: Union[str, Sequence[str], None] = '5f5e25387acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candle', sa.Column('interval', sa.String(), nullable=True))
    op.execute("UPDATE candle SET interval = '1d'")
    
    # Delete duplicates
    op.execute("""
        DELETE FROM candle
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY symbol_id, interval, timestamp
                           ORDER BY id
                       ) as row_num
                FROM candle
            ) t
            WHERE row_num > 1
        )
    """)
    
    op.alter_column('candle', 'interval', nullable=False)
    op.create_index(op.f('ix_candle_interval'), 'candle', ['interval'], unique=False)
    op.create_unique_constraint('uq_candle_symbol_interval_timestamp', 'candle', ['symbol_id', 'interval', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candle_symbol_interval_timestamp', 'candle', type_='unique')
    op.drop_index(op.f('ix_candle_interval'), table_name='candle')
    op.drop_column('candle', 'interval')
    # ### end Alembic commands ###
